company = Encoding.ASCII.GetString(msgPartail, offset, 7).Trim();
actno = Encoding.ASCII.GetString(msgPartail, offset += 7, 7).Trim();
exhno = Encoding.ASCII.GetString(msgPartail, offset += 7, 6).Trim();
ordno = Encoding.ASCII.GetString(msgPartail, offset += 6, 6).Trim();
trdno = Encoding.ASCII.GetString(msgPartail, offset += 6, 10).Trim();
dno = Encoding.ASCII.GetString(msgPartail, offset += 10, 3).Trim();
trddt = Encoding.ASCII.GetString(msgPartail, offset += 3, 8).Trim();
SetSide = Encoding.ASCII.GetString(msgPartail, offset += 8, 1).Trim();
SetComtype = Encoding.ASCII.GetString(msgPartail, offset += 1, 1).Trim();
comno = Encoding.ASCII.GetString(msgPartail, offset += 1, 7).Trim();
comym = Encoding.ASCII.GetString(msgPartail, offset += 7, 6).Trim();
stkprc = ConverDecimal(Encoding.ASCII.GetString(msgPartail, offset += 6, 13).Trim(), 6);
SetCallput = Encoding.ASCII.GetString(msgPartail, offset += 13, 1).Trim();
oTqty = Encoding.ASCII.GetString(msgPartail, offset += 1, 5).Trim();
trdpre = ConverDecimal(Encoding.ASCII.GetString(msgPartail, offset += 5, 13).Trim(), 6);
mktprc = ConverDecimal(Encoding.ASCII.GetString(msgPartail, offset += 13, 13).Trim(), 6);
prtlos = ConverDecimal(Encoding.ASCII.GetString(msgPartail, offset += 13, 14).Trim(), 2);
iamt = ConverDecimal(Encoding.ASCII.GetString(msgPartail, offset += 14, 13).Trim(), 2);
mamt = ConverDecimal(Encoding.ASCII.GetString(msgPartail, offset += 13, 13).Trim(), 2);
currency = Encoding.ASCII.GetString(msgPartail, offset += 13, 3).Trim();
trdprc = ConverDecimal(Encoding.ASCII.GetString(msgPartail, offset += 3, 14).Trim(), 6);
ordno2 = Encoding.ASCII.GetString(msgPartail, offset += 14, 6).Trim();
trdprc2 = Encoding.ASCII.GetString(msgPartail, offset += 6, 10).Trim();
dno2 = Encoding.ASCII.GetString(msgPartail, offset += 10, 3).Trim();
trddt2 = Encoding.ASCII.GetString(msgPartail, offset += 3, 8).Trim();
side2 = Encoding.ASCII.GetString(msgPartail, offset += 8, 1).Trim();
comtype = Encoding.ASCII.GetString(msgPartail, offset += 1, 1).Trim();
comno = Encoding.ASCII.GetString(msgPartail, offset += 1, 7).Trim();
comym = Encoding.ASCII.GetString(msgPartail, offset += 7, 6).Trim();
stkprc = ConverDecimal(Encoding.ASCII.GetString(msgPartail, offset += 6, 13).Trim(), 6);
callput = Encoding.ASCII.GetString(msgPartail, offset += 13, 1).Trim();
oTqty2 = Encoding.ASCII.GetString(msgPartail, offset += 1, 5).Trim();
trdpre2 = ConverDecimal(Encoding.ASCII.GetString(msgPartail, offset += 5, 13).Trim(), 6);
mktprc2 = ConverDecimal(Encoding.ASCII.GetString(msgPartail, offset += 13, 13).Trim(), 6);
prtlos2 = ConverDecimal(Encoding.ASCII.GetString(msgPartail, offset += 13, 14).Trim(), 2);
iamt2 = ConverDecimal(Encoding.ASCII.GetString(msgPartail, offset += 14, 13).Trim(), 2);
mamt2 = ConverDecimal(Encoding.ASCII.GetString(msgPartail, offset += 13, 13).Trim(), 2);
currency = Encoding.ASCII.GetString(msgPartail, offset += 13, 3).Trim();
trdprc2 = ConverDecimal(Encoding.ASCII.GetString(msgPartail, offset += 3, 14).Trim(), 6);
dtrade = Encoding.ASCII.GetString(msgPartail, offset += 14, 1);
COMPOSE = Encoding.ASCII.GetString(msgPartail, offset += 1, 1);
ORIGIN1 = Encoding.ASCII.GetString(msgPartail, offset += 1, 1);
ORIGIN2 = Encoding.ASCII.GetString(msgPartail, offset += 1, 1);
